# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguredProcesserIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processerID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguredProcesserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('targetProcessor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Status', to='workflow.ConfiguredProcessor')),
                ('targetWorkflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=200)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(default=None)),
                ('endDate', models.DateTimeField(default=None)),
                ('status', models.IntegerField(default=0)),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='ProcesserInputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=200)),
                ('processor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatcher.ConfiguredProcesserIO')),
            ],
        ),
        migrations.CreateModel(
            name='ProcesserOutputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=200)),
                ('processor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatcher.ConfiguredProcesserIO')),
            ],
        ),
        migrations.AddField(
            model_name='configuredprocesserio',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatcher.Mission'),
        ),
    ]
