# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguredProcessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.TextField()),
                ('inputs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('optional', models.BooleanField(default=False)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.DataType')),
            ],
        ),
        migrations.CreateModel(
            name='MissionContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True)),
                ('name', models.CharField(max_length=100, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.DataType')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('jar_file', models.FilePathField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('description', models.TextField(verbose_name='\u7b80\u4ecb')),
                ('icon', models.CharField(max_length=20, verbose_name='\u56fe\u6807\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='SelectionParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hint', models.CharField(blank=True, max_length=130)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hint', models.CharField(blank=True, max_length=130)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='processor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.ProcessorCategory', verbose_name='\u6240\u5c5e\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='dispatcher.Processor'),
        ),
        migrations.AddField(
            model_name='output',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='dispatcher.Processor'),
        ),
        migrations.AddField(
            model_name='input',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='dispatcher.Processor'),
        ),
        migrations.AddField(
            model_name='configuredprocessor',
            name='meta_processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.Processor'),
        ),
        migrations.AddField(
            model_name='configuredprocessor',
            name='mission_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.MissionContext'),
        ),
    ]
