# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
