# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0003_auto_20161213_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuredprocessorstatus',
            name='targetMission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatcher.Mission'),
        ),
    ]
