# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0004_configuredprocessorstatus_targetmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuredprocessorstatus',
            name='targetProcessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Status', to='workflow.ConfiguredProcessor'),
        ),
    ]
