# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguredParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=30)),
                ('val', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguredProcessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_id', models.CharField(default=0, max_length=30)),
                ('loc_x', models.FloatField(default=0.0)),
                ('loc_y', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10)),
                ('slug', models.SlugField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InputChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.DataType')),
            ],
        ),
        migrations.CreateModel(
            name='OutputChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.DataType')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('hint', models.CharField(blank=True, default='', max_length=130)),
                ('value', models.CharField(blank=True, default='', max_length=225)),
                ('optional', models.BooleanField(default=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParameterSelectionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=30)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='workflow.ParameterSelection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParameterText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('exec_file', models.FileField(null=True, upload_to=b'exec_files')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=20, verbose_name='\u56fe\u6807\u540d\u79f0')),
                ('parent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workflow.ProcessorCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='processor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processors', to='workflow.ProcessorCategory'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='workflow.Processor'),
        ),
        migrations.AddField(
            model_name='outputchannel',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='workflow.Processor'),
        ),
        migrations.AddField(
            model_name='inputchannel',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='workflow.Processor'),
        ),
        migrations.AddField(
            model_name='connection',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.InputChannel'),
        ),
        migrations.AddField(
            model_name='connection',
            name='input_processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_connections', to='workflow.ConfiguredProcessor'),
        ),
        migrations.AddField(
            model_name='connection',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.OutputChannel'),
        ),
        migrations.AddField(
            model_name='connection',
            name='output_processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_connections', to='workflow.ConfiguredProcessor'),
        ),
        migrations.AddField(
            model_name='connection',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='workflow.Workflow'),
        ),
        migrations.AddField(
            model_name='configuredprocessor',
            name='meta_processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Processor'),
        ),
        migrations.AddField(
            model_name='configuredprocessor',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processors', to='workflow.Workflow'),
        ),
        migrations.AddField(
            model_name='configuredparameter',
            name='configured_processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='workflow.ConfiguredProcessor'),
        ),
        migrations.AddField(
            model_name='configuredparameter',
            name='meta_parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Parameter'),
        ),
        migrations.AddField(
            model_name='configuredparameter',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='workflow.Workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together=set([('label', 'processor'), ('content_type', 'object_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='outputchannel',
            unique_together=set([('processor', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='inputchannel',
            unique_together=set([('processor', 'name')]),
        ),
    ]
