# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuredinput',
            name='meta_input',
        ),
        migrations.RemoveField(
            model_name='configuredoutput',
            name='meta_output',
        ),
        migrations.AlterField(
            model_name='connection',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Input'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Output'),
        ),
        migrations.DeleteModel(
            name='ConfiguredInput',
        ),
        migrations.DeleteModel(
            name='ConfiguredOutput',
        ),
    ]
