# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20161124_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='processor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='params', to='workflow.Processor'),
            preserve_default=False,
        ),
    ]
