# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_parameter_processor'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.DataType')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='workflow.Processor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutputChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.DataType')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='workflow.Processor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='input',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='input',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='output',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='output',
            name='processor',
        ),
        migrations.AlterField(
            model_name='connection',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.InputChannel'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.OutputChannel'),
        ),
        migrations.DeleteModel(
            name='Input',
        ),
        migrations.DeleteModel(
            name='Output',
        ),
    ]
