# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processorcategory',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ConfiguredCategory', to='workflow.Category'),
        ),
    ]
