# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20161124_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='exec_file',
            field=models.FileField(null=True, upload_to=b'exec_files'),
        ),
    ]
