# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_auto_20170103_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterdatabase',
            name='database',
        ),
        migrations.AlterField(
            model_name='category',
            name='picture_path',
            field=models.FileField(null=True, upload_to=b'Picture/'),
        ),
    ]
