# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_auto_20170118_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterCheckbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to=b'Document/'),
        ),
        migrations.AddField(
            model_name='processor',
            name='visualization_category',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
