# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_auto_20170118_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='is_local',
            field=models.BooleanField(default=True),
        ),
    ]
